// Header file for M5StackBluetoothContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "bluetooth_context.h"


namespace omusubi {


/**
 * @brief M5StackBluetoothContext - Implementation of BluetoothContext
 *
 * This class implements the pure virtual functions from BluetoothContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackBluetoothContext : public BluetoothContext {
public:
    // Constructor
    M5StackBluetoothContext() = default;

    // Destructor
    virtual ~M5StackBluetoothContext() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackBluetoothContext(const M5StackBluetoothContext&) = delete;
    M5StackBluetoothContext& operator=(const M5StackBluetoothContext&) = delete;

    // Delete move constructor and assignment operator
    M5StackBluetoothContext(M5StackBluetoothContext&&) = delete;
    M5StackBluetoothContext& operator=(M5StackBluetoothContext&&) = delete;

    // Override pure virtual methods from base class

    size_t read(span<uint8_t> buffer) override;

    size_t available() const override;

    size_t read_line(span<char> buffer) override;

    size_t write(span<const uint8_t> data) const override;

    size_t write_text(span<const char> text) const override;

    bool connect() override;

    bool disconnect() override;

    bool is_connected() const override;

    bool start_scan() override;

    bool stop_scan() override;

    uint8_t get_found_count() const override;

    std::string_view get_found_name(uint8_t index) const override;

    int32_t get_found_signal_strength(uint8_t index) const override;

};


} // namespace omusubi

