// Header file for M5StackConnectableContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "connectable_context.h"


namespace omusubi {


/**
 * @brief M5StackConnectableContext - Implementation of ConnectableContext
 *
 * This class implements the pure virtual functions from ConnectableContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackConnectableContext : public ConnectableContext {
public:
    // Constructor
    M5StackConnectableContext() = default;

    // Destructor
    virtual ~M5StackConnectableContext() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackConnectableContext(const M5StackConnectableContext&) = delete;
    M5StackConnectableContext& operator=(const M5StackConnectableContext&) = delete;

    // Delete move constructor and assignment operator
    M5StackConnectableContext(M5StackConnectableContext&&) = delete;
    M5StackConnectableContext& operator=(M5StackConnectableContext&&) = delete;

    // Override pure virtual methods from base class

    SerialContext get_serial_context(uint8_t port) const override;

    uint8_t get_serial_count() const override;

    BluetoothContext get_bluetooth_context() const override;

    WiFiContext get_wifi_context() const override;

    BLEContext get_ble_context() const override;

};


} // namespace omusubi

