// Header file for M5StackLogOutput
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "log_output.h"


namespace omusubi {


/**
 * @brief M5StackLogOutput - Implementation of LogOutput
 *
 * This class implements the pure virtual functions from LogOutput.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackLogOutput : public LogOutput {
public:
    // Constructor
    M5StackLogOutput() = default;

    // Destructor
    virtual ~M5StackLogOutput() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackLogOutput(const M5StackLogOutput&) = delete;
    M5StackLogOutput& operator=(const M5StackLogOutput&) = delete;

    // Delete move constructor and assignment operator
    M5StackLogOutput(M5StackLogOutput&&) = delete;
    M5StackLogOutput& operator=(M5StackLogOutput&&) = delete;

    // Override pure virtual methods from base class

    void write(LogLevel level, std::string_view message) override;

};


} // namespace omusubi

