// Header file for M5StackMeasurable3D
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "measurable3d.h"


namespace omusubi {


/**
 * @brief M5StackMeasurable3D - Implementation of Measurable3D
 *
 * This class implements the pure virtual functions from Measurable3D.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackMeasurable3D : public Measurable3D {
public:
    // Constructor
    M5StackMeasurable3D() = default;

    // Destructor
    virtual ~M5StackMeasurable3D() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackMeasurable3D(const M5StackMeasurable3D&) = delete;
    M5StackMeasurable3D& operator=(const M5StackMeasurable3D&) = delete;

    // Delete move constructor and assignment operator
    M5StackMeasurable3D(M5StackMeasurable3D&&) = delete;
    M5StackMeasurable3D& operator=(M5StackMeasurable3D&&) = delete;

    // Override pure virtual methods from base class

    Vector3 get_values() const override;

};


} // namespace omusubi

