// Header file for M5StackScannableContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "scannable_context.h"


namespace omusubi {


/**
 * @brief M5StackScannableContext - Implementation of ScannableContext
 *
 * This class implements the pure virtual functions from ScannableContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackScannableContext : public ScannableContext {
public:
    // Constructor
    M5StackScannableContext() = default;

    // Destructor
    virtual ~M5StackScannableContext() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackScannableContext(const M5StackScannableContext&) = delete;
    M5StackScannableContext& operator=(const M5StackScannableContext&) = delete;

    // Delete move constructor and assignment operator
    M5StackScannableContext(M5StackScannableContext&&) = delete;
    M5StackScannableContext& operator=(M5StackScannableContext&&) = delete;

    // Override pure virtual methods from base class

    BluetoothContext get_bluetooth_context() const override;

    WiFiContext get_wifi_context() const override;

    BLEContext get_ble_context() const override;

};


} // namespace omusubi

