// Header file for M5StackSystemInfoContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "system_info_context.h"


namespace omusubi {


/**
 * @brief M5StackSystemInfoContext - Implementation of SystemInfoContext
 *
 * This class implements the pure virtual functions from SystemInfoContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackSystemInfoContext : public SystemInfoContext {
public:
    // Constructor
    M5StackSystemInfoContext() = default;

    // Destructor
    virtual ~M5StackSystemInfoContext() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackSystemInfoContext(const M5StackSystemInfoContext&) = delete;
    M5StackSystemInfoContext& operator=(const M5StackSystemInfoContext&) = delete;

    // Delete move constructor and assignment operator
    M5StackSystemInfoContext(M5StackSystemInfoContext&&) = delete;
    M5StackSystemInfoContext& operator=(M5StackSystemInfoContext&&) = delete;

    // Override pure virtual methods from base class

    std::string_view get_device_name() const override;

    std::string_view get_firmware_version() const override;

    uint64_t get_chip_id() const override;

    uint32_t get_uptime_ms() const override;

    uint32_t get_free_memory() const override;

};


} // namespace omusubi

