// Header file for M5StackDisplayable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "displayable.h"


namespace omusubi {


/**
 * @brief M5StackDisplayable - Implementation of Displayable
 *
 * This class implements the pure virtual functions from Displayable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackDisplayable : public Displayable {
public:
    // Constructor
    M5StackDisplayable() = default;

    // Destructor
    virtual ~M5StackDisplayable() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackDisplayable(const M5StackDisplayable&) = delete;
    M5StackDisplayable& operator=(const M5StackDisplayable&) = delete;

    // Delete move constructor and assignment operator
    M5StackDisplayable(M5StackDisplayable&&) = delete;
    M5StackDisplayable& operator=(M5StackDisplayable&&) = delete;

    // Override pure virtual methods from base class

    void display(std::string_view text) override;

};


} // namespace omusubi

