// Header file for m5stackMeasurable1D
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "measurable1d.h"


namespace omusubi {


/**
 * @brief m5stackMeasurable1D - Implementation of Measurable1D
 *
 * This class implements the pure virtual functions from Measurable1D.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackMeasurable1D : public Measurable1D {
public:
    // Constructor
    m5stackMeasurable1D() = default;

    // Destructor
    virtual ~m5stackMeasurable1D() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackMeasurable1D(const m5stackMeasurable1D&) = delete;
    m5stackMeasurable1D& operator=(const m5stackMeasurable1D&) = delete;

    // Delete move constructor and assignment operator
    m5stackMeasurable1D(m5stackMeasurable1D&&) = delete;
    m5stackMeasurable1D& operator=(m5stackMeasurable1D&&) = delete;

    // Override pure virtual methods from base class

    float get_value() const override;

};


} // namespace omusubi

