// Header file for M5StackTextWritable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "text_writable.h"


namespace omusubi {


/**
 * @brief M5StackTextWritable - Implementation of TextWritable
 *
 * This class implements the pure virtual functions from TextWritable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackTextWritable : public TextWritable {
public:
    // Constructor
    M5StackTextWritable() = default;

    // Destructor
    virtual ~M5StackTextWritable() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackTextWritable(const M5StackTextWritable&) = delete;
    M5StackTextWritable& operator=(const M5StackTextWritable&) = delete;

    // Delete move constructor and assignment operator
    M5StackTextWritable(M5StackTextWritable&&) = delete;
    M5StackTextWritable& operator=(M5StackTextWritable&&) = delete;

    // Override pure virtual methods from base class

    size_t write_text(span<const char> text) const override;

};


} // namespace omusubi

