// Header file for M5StackPowerContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "power_context.h"


namespace omusubi {


/**
 * @brief M5StackPowerContext - Implementation of PowerContext
 *
 * This class implements the pure virtual functions from PowerContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackPowerContext : public PowerContext {
public:
    // Constructor
    M5StackPowerContext() = default;

    // Destructor
    virtual ~M5StackPowerContext() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackPowerContext(const M5StackPowerContext&) = delete;
    M5StackPowerContext& operator=(const M5StackPowerContext&) = delete;

    // Delete move constructor and assignment operator
    M5StackPowerContext(M5StackPowerContext&&) = delete;
    M5StackPowerContext& operator=(M5StackPowerContext&&) = delete;

    // Override pure virtual methods from base class

    PowerState get_power_state() const override;

    uint8_t get_battery_level() const override;

    bool is_charging() const override;

};


} // namespace omusubi

