// Header file for m5stackWiFiContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "wi_fi_context.h"


namespace omusubi {


/**
 * @brief m5stackWiFiContext - Implementation of WiFiContext
 *
 * This class implements the pure virtual functions from WiFiContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackWiFiContext : public WiFiContext {
public:
    // Constructor
    m5stackWiFiContext() = default;

    // Destructor
    virtual ~m5stackWiFiContext() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackWiFiContext(const m5stackWiFiContext&) = delete;
    m5stackWiFiContext& operator=(const m5stackWiFiContext&) = delete;

    // Delete move constructor and assignment operator
    m5stackWiFiContext(m5stackWiFiContext&&) = delete;
    m5stackWiFiContext& operator=(m5stackWiFiContext&&) = delete;

    // Override pure virtual methods from base class

    bool connect() override;

    bool disconnect() override;

    bool is_connected() const override;

    bool start_scan() override;

    bool stop_scan() override;

    uint8_t get_found_count() const override;

    std::string_view get_found_name(uint8_t index) const override;

    int32_t get_found_signal_strength(uint8_t index) const override;

};


} // namespace omusubi

