// Header file for M5StackPressable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "pressable.h"


namespace omusubi {


/**
 * @brief M5StackPressable - Implementation of Pressable
 *
 * This class implements the pure virtual functions from Pressable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackPressable : public Pressable {
public:
    // Constructor
    M5StackPressable() = default;

    // Destructor
    virtual ~M5StackPressable() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackPressable(const M5StackPressable&) = delete;
    M5StackPressable& operator=(const M5StackPressable&) = delete;

    // Delete move constructor and assignment operator
    M5StackPressable(M5StackPressable&&) = delete;
    M5StackPressable& operator=(M5StackPressable&&) = delete;

    // Override pure virtual methods from base class

    ButtonState get_state() const override;

};


} // namespace omusubi

