// Header file for M5StackSerialContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "serial_context.h"


namespace omusubi {


/**
 * @brief M5StackSerialContext - Implementation of SerialContext
 *
 * This class implements the pure virtual functions from SerialContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackSerialContext : public SerialContext {
public:
    // Constructor
    M5StackSerialContext() = default;

    // Destructor
    virtual ~M5StackSerialContext() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackSerialContext(const M5StackSerialContext&) = delete;
    M5StackSerialContext& operator=(const M5StackSerialContext&) = delete;

    // Delete move constructor and assignment operator
    M5StackSerialContext(M5StackSerialContext&&) = delete;
    M5StackSerialContext& operator=(M5StackSerialContext&&) = delete;

    // Override pure virtual methods from base class

    size_t read(span<uint8_t> buffer) override;

    size_t available() const override;

    size_t read_line(span<char> buffer) override;

    size_t write(span<const uint8_t> data) const override;

    size_t write_text(span<const char> text) const override;

    bool connect() override;

    bool disconnect() override;

    bool is_connected() const override;

};


} // namespace omusubi

