// Header file for M5StackByteWritable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "byte_writable.h"


namespace omusubi {


/**
 * @brief M5StackByteWritable - Implementation of ByteWritable
 *
 * This class implements the pure virtual functions from ByteWritable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackByteWritable : public ByteWritable {
public:
    // Constructor
    M5StackByteWritable() = default;

    // Destructor
    virtual ~M5StackByteWritable() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackByteWritable(const M5StackByteWritable&) = delete;
    M5StackByteWritable& operator=(const M5StackByteWritable&) = delete;

    // Delete move constructor and assignment operator
    M5StackByteWritable(M5StackByteWritable&&) = delete;
    M5StackByteWritable& operator=(M5StackByteWritable&&) = delete;

    // Override pure virtual methods from base class

    size_t write(span<const uint8_t> data) const override;

};


} // namespace omusubi

