// Header file for m5stackBLECharacteristic
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "blecharacteristic.h"


namespace omusubi {


/**
 * @brief m5stackBLECharacteristic - Implementation of BLECharacteristic
 *
 * This class implements the pure virtual functions from BLECharacteristic.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackBLECharacteristic : public BLECharacteristic {
public:
    // Constructor
    m5stackBLECharacteristic() = default;

    // Destructor
    virtual ~m5stackBLECharacteristic() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackBLECharacteristic(const m5stackBLECharacteristic&) = delete;
    m5stackBLECharacteristic& operator=(const m5stackBLECharacteristic&) = delete;

    // Delete move constructor and assignment operator
    m5stackBLECharacteristic(m5stackBLECharacteristic&&) = delete;
    m5stackBLECharacteristic& operator=(m5stackBLECharacteristic&&) = delete;

    // Override pure virtual methods from base class

    size_t read(span<uint8_t> buffer) override;

    size_t available() const override;

    size_t write(span<const uint8_t> data) const override;

};


} // namespace omusubi

