// Header file for m5stackSerialContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "serial_context.h"


namespace omusubi {


/**
 * @brief m5stackSerialContext - Implementation of SerialContext
 *
 * This class implements the pure virtual functions from SerialContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackSerialContext : public SerialContext {
public:
    // Constructor
    m5stackSerialContext() = default;

    // Destructor
    virtual ~m5stackSerialContext() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackSerialContext(const m5stackSerialContext&) = delete;
    m5stackSerialContext& operator=(const m5stackSerialContext&) = delete;

    // Delete move constructor and assignment operator
    m5stackSerialContext(m5stackSerialContext&&) = delete;
    m5stackSerialContext& operator=(m5stackSerialContext&&) = delete;

    // Override pure virtual methods from base class

    size_t read(span<uint8_t> buffer) override;

    size_t available() const override;

    size_t read_line(span<char> buffer) override;

    size_t write(span<const uint8_t> data) const override;

    size_t write_text(span<const char> text) const override;

    bool connect() override;

    bool disconnect() override;

    bool is_connected() const override;

};


} // namespace omusubi

