// Header file for m5stackPressable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "pressable.h"


namespace omusubi {


/**
 * @brief m5stackPressable - Implementation of Pressable
 *
 * This class implements the pure virtual functions from Pressable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackPressable : public Pressable {
public:
    // Constructor
    m5stackPressable() = default;

    // Destructor
    virtual ~m5stackPressable() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackPressable(const m5stackPressable&) = delete;
    m5stackPressable& operator=(const m5stackPressable&) = delete;

    // Delete move constructor and assignment operator
    m5stackPressable(m5stackPressable&&) = delete;
    m5stackPressable& operator=(m5stackPressable&&) = delete;

    // Override pure virtual methods from base class

    ButtonState get_state() const override;

};


} // namespace omusubi

