// Header file for m5stackSystemInfoContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "system_info_context.h"


namespace omusubi {


/**
 * @brief m5stackSystemInfoContext - Implementation of SystemInfoContext
 *
 * This class implements the pure virtual functions from SystemInfoContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackSystemInfoContext : public SystemInfoContext {
public:
    // Constructor
    m5stackSystemInfoContext() = default;

    // Destructor
    virtual ~m5stackSystemInfoContext() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackSystemInfoContext(const m5stackSystemInfoContext&) = delete;
    m5stackSystemInfoContext& operator=(const m5stackSystemInfoContext&) = delete;

    // Delete move constructor and assignment operator
    m5stackSystemInfoContext(m5stackSystemInfoContext&&) = delete;
    m5stackSystemInfoContext& operator=(m5stackSystemInfoContext&&) = delete;

    // Override pure virtual methods from base class

    std::string_view get_device_name() const override;

    std::string_view get_firmware_version() const override;

    uint64_t get_chip_id() const override;

    uint32_t get_uptime_ms() const override;

    uint32_t get_free_memory() const override;

};


} // namespace omusubi

