// Header file for m5stackBLEContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "blecontext.h"


namespace omusubi {


/**
 * @brief m5stackBLEContext - Implementation of BLEContext
 *
 * This class implements the pure virtual functions from BLEContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackBLEContext : public BLEContext {
public:
    // Constructor
    m5stackBLEContext() = default;

    // Destructor
    virtual ~m5stackBLEContext() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackBLEContext(const m5stackBLEContext&) = delete;
    m5stackBLEContext& operator=(const m5stackBLEContext&) = delete;

    // Delete move constructor and assignment operator
    m5stackBLEContext(m5stackBLEContext&&) = delete;
    m5stackBLEContext& operator=(m5stackBLEContext&&) = delete;

    // Override pure virtual methods from base class

    bool connect() override;

    bool disconnect() override;

    bool is_connected() const override;

    bool start_scan() override;

    bool stop_scan() override;

    uint8_t get_found_count() const override;

    std::string_view get_found_name(uint8_t index) const override;

    int32_t get_found_signal_strength(uint8_t index) const override;

};


} // namespace omusubi

