// Header file for m5stackSystemContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "system_context.h"


namespace omusubi {


/**
 * @brief m5stackSystemContext - Implementation of SystemContext
 *
 * This class implements the pure virtual functions from SystemContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackSystemContext : public SystemContext {
public:
    // Constructor
    m5stackSystemContext() = default;

    // Destructor
    virtual ~m5stackSystemContext() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackSystemContext(const m5stackSystemContext&) = delete;
    m5stackSystemContext& operator=(const m5stackSystemContext&) = delete;

    // Delete move constructor and assignment operator
    m5stackSystemContext(m5stackSystemContext&&) = delete;
    m5stackSystemContext& operator=(m5stackSystemContext&&) = delete;

    // Override pure virtual methods from base class

    void begin() override;

    void update() override;

    void delay(uint32_t ms) override;

    void reset() override;

    ConnectableContext get_connectable_context() const override;

    ScannableContext get_scannable_context() const override;

    SensorContext get_sensor_context() const override;

    InputContext get_input_context() const override;

    OutputContext get_output_context() const override;

    SystemInfoContext get_system_info_context() const override;

    PowerContext get_power_context() const override;

};


} // namespace omusubi

