// Header file for M5StackBLECharacteristic
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "blecharacteristic.h"


namespace omusubi {


/**
 * @brief M5StackBLECharacteristic - Implementation of BLECharacteristic
 *
 * This class implements the pure virtual functions from BLECharacteristic.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackBLECharacteristic : public BLECharacteristic {
public:
    // Constructor
    M5StackBLECharacteristic() = default;

    // Destructor
    virtual ~M5StackBLECharacteristic() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackBLECharacteristic(const M5StackBLECharacteristic&) = delete;
    M5StackBLECharacteristic& operator=(const M5StackBLECharacteristic&) = delete;

    // Delete move constructor and assignment operator
    M5StackBLECharacteristic(M5StackBLECharacteristic&&) = delete;
    M5StackBLECharacteristic& operator=(M5StackBLECharacteristic&&) = delete;

    // Override pure virtual methods from base class

    size_t read(span<uint8_t> buffer) override;

    size_t available() const override;

    size_t write(span<const uint8_t> data) const override;

};


} // namespace omusubi

