// Header file for m5stackScannable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "scannable.h"


namespace omusubi {


/**
 * @brief m5stackScannable - Implementation of Scannable
 *
 * This class implements the pure virtual functions from Scannable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackScannable : public Scannable {
public:
    // Constructor
    m5stackScannable() = default;

    // Destructor
    virtual ~m5stackScannable() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackScannable(const m5stackScannable&) = delete;
    m5stackScannable& operator=(const m5stackScannable&) = delete;

    // Delete move constructor and assignment operator
    m5stackScannable(m5stackScannable&&) = delete;
    m5stackScannable& operator=(m5stackScannable&&) = delete;

    // Override pure virtual methods from base class

    bool start_scan() override;

    bool stop_scan() override;

    uint8_t get_found_count() const override;

    std::string_view get_found_name(uint8_t index) const override;

    int32_t get_found_signal_strength(uint8_t index) const override;

};


} // namespace omusubi

