// Header file for m5stackLogOutput
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "log_output.h"


namespace omusubi {


/**
 * @brief m5stackLogOutput - Implementation of LogOutput
 *
 * This class implements the pure virtual functions from LogOutput.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackLogOutput : public LogOutput {
public:
    // Constructor
    m5stackLogOutput() = default;

    // Destructor
    virtual ~m5stackLogOutput() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackLogOutput(const m5stackLogOutput&) = delete;
    m5stackLogOutput& operator=(const m5stackLogOutput&) = delete;

    // Delete move constructor and assignment operator
    m5stackLogOutput(m5stackLogOutput&&) = delete;
    m5stackLogOutput& operator=(m5stackLogOutput&&) = delete;

    // Override pure virtual methods from base class

    void write(LogLevel level, std::string_view message) override;

};


} // namespace omusubi

