// Header file for M5StackConnectable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "connectable.h"


namespace omusubi {


/**
 * @brief M5StackConnectable - Implementation of Connectable
 *
 * This class implements the pure virtual functions from Connectable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackConnectable : public Connectable {
public:
    // Constructor
    M5StackConnectable() = default;

    // Destructor
    virtual ~M5StackConnectable() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackConnectable(const M5StackConnectable&) = delete;
    M5StackConnectable& operator=(const M5StackConnectable&) = delete;

    // Delete move constructor and assignment operator
    M5StackConnectable(M5StackConnectable&&) = delete;
    M5StackConnectable& operator=(M5StackConnectable&&) = delete;

    // Override pure virtual methods from base class

    bool connect() override;

    bool disconnect() override;

    bool is_connected() const override;

};


} // namespace omusubi

