// Header file for m5stackBluetoothContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "bluetooth_context.h"


namespace omusubi {


/**
 * @brief m5stackBluetoothContext - Implementation of BluetoothContext
 *
 * This class implements the pure virtual functions from BluetoothContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackBluetoothContext : public BluetoothContext {
public:
    // Constructor
    m5stackBluetoothContext() = default;

    // Destructor
    virtual ~m5stackBluetoothContext() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackBluetoothContext(const m5stackBluetoothContext&) = delete;
    m5stackBluetoothContext& operator=(const m5stackBluetoothContext&) = delete;

    // Delete move constructor and assignment operator
    m5stackBluetoothContext(m5stackBluetoothContext&&) = delete;
    m5stackBluetoothContext& operator=(m5stackBluetoothContext&&) = delete;

    // Override pure virtual methods from base class

    size_t read(span<uint8_t> buffer) override;

    size_t available() const override;

    size_t read_line(span<char> buffer) override;

    size_t write(span<const uint8_t> data) const override;

    size_t write_text(span<const char> text) const override;

    bool connect() override;

    bool disconnect() override;

    bool is_connected() const override;

    bool start_scan() override;

    bool stop_scan() override;

    uint8_t get_found_count() const override;

    std::string_view get_found_name(uint8_t index) const override;

    int32_t get_found_signal_strength(uint8_t index) const override;

};


} // namespace omusubi

