// Header file for M5StackSystemContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "system_context.h"


namespace omusubi {


/**
 * @brief M5StackSystemContext - Implementation of SystemContext
 *
 * This class implements the pure virtual functions from SystemContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackSystemContext : public SystemContext {
public:
    // Constructor
    M5StackSystemContext() = default;

    // Destructor
    virtual ~M5StackSystemContext() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackSystemContext(const M5StackSystemContext&) = delete;
    M5StackSystemContext& operator=(const M5StackSystemContext&) = delete;

    // Delete move constructor and assignment operator
    M5StackSystemContext(M5StackSystemContext&&) = delete;
    M5StackSystemContext& operator=(M5StackSystemContext&&) = delete;

    // Override pure virtual methods from base class

    void begin() override;

    void update() override;

    void delay(uint32_t ms) override;

    void reset() override;

    ConnectableContext get_connectable_context() const override;

    ScannableContext get_scannable_context() const override;

    SensorContext get_sensor_context() const override;

    InputContext get_input_context() const override;

    OutputContext get_output_context() const override;

    SystemInfoContext get_system_info_context() const override;

    PowerContext get_power_context() const override;

};


} // namespace omusubi

