// Header file for M5StackTextReadable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "text_readable.h"


namespace omusubi {


/**
 * @brief M5StackTextReadable - Implementation of TextReadable
 *
 * This class implements the pure virtual functions from TextReadable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackTextReadable : public TextReadable {
public:
    // Constructor
    M5StackTextReadable() = default;

    // Destructor
    virtual ~M5StackTextReadable() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackTextReadable(const M5StackTextReadable&) = delete;
    M5StackTextReadable& operator=(const M5StackTextReadable&) = delete;

    // Delete move constructor and assignment operator
    M5StackTextReadable(M5StackTextReadable&&) = delete;
    M5StackTextReadable& operator=(M5StackTextReadable&&) = delete;

    // Override pure virtual methods from base class

    size_t read_line(span<char> buffer) override;

};


} // namespace omusubi

