// Header file for M5StackMeasurable1D
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "measurable1d.h"


namespace omusubi {


/**
 * @brief M5StackMeasurable1D - Implementation of Measurable1D
 *
 * This class implements the pure virtual functions from Measurable1D.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackMeasurable1D : public Measurable1D {
public:
    // Constructor
    M5StackMeasurable1D() = default;

    // Destructor
    virtual ~M5StackMeasurable1D() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackMeasurable1D(const M5StackMeasurable1D&) = delete;
    M5StackMeasurable1D& operator=(const M5StackMeasurable1D&) = delete;

    // Delete move constructor and assignment operator
    M5StackMeasurable1D(M5StackMeasurable1D&&) = delete;
    M5StackMeasurable1D& operator=(M5StackMeasurable1D&&) = delete;

    // Override pure virtual methods from base class

    float get_value() const override;

};


} // namespace omusubi

