// Header file for M5StackBLEContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "blecontext.h"


namespace omusubi {


/**
 * @brief M5StackBLEContext - Implementation of BLEContext
 *
 * This class implements the pure virtual functions from BLEContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackBLEContext : public BLEContext {
public:
    // Constructor
    M5StackBLEContext() = default;

    // Destructor
    virtual ~M5StackBLEContext() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackBLEContext(const M5StackBLEContext&) = delete;
    M5StackBLEContext& operator=(const M5StackBLEContext&) = delete;

    // Delete move constructor and assignment operator
    M5StackBLEContext(M5StackBLEContext&&) = delete;
    M5StackBLEContext& operator=(M5StackBLEContext&&) = delete;

    // Override pure virtual methods from base class

    bool connect() override;

    bool disconnect() override;

    bool is_connected() const override;

    bool start_scan() override;

    bool stop_scan() override;

    uint8_t get_found_count() const override;

    std::string_view get_found_name(uint8_t index) const override;

    int32_t get_found_signal_strength(uint8_t index) const override;

};


} // namespace omusubi

