// Header file for M5StackScannable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "scannable.h"


namespace omusubi {


/**
 * @brief M5StackScannable - Implementation of Scannable
 *
 * This class implements the pure virtual functions from Scannable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackScannable : public Scannable {
public:
    // Constructor
    M5StackScannable() = default;

    // Destructor
    virtual ~M5StackScannable() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackScannable(const M5StackScannable&) = delete;
    M5StackScannable& operator=(const M5StackScannable&) = delete;

    // Delete move constructor and assignment operator
    M5StackScannable(M5StackScannable&&) = delete;
    M5StackScannable& operator=(M5StackScannable&&) = delete;

    // Override pure virtual methods from base class

    bool start_scan() override;

    bool stop_scan() override;

    uint8_t get_found_count() const override;

    std::string_view get_found_name(uint8_t index) const override;

    int32_t get_found_signal_strength(uint8_t index) const override;

};


} // namespace omusubi

