// Header file for m5stackScannableContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "scannable_context.h"


namespace omusubi {


/**
 * @brief m5stackScannableContext - Implementation of ScannableContext
 *
 * This class implements the pure virtual functions from ScannableContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackScannableContext : public ScannableContext {
public:
    // Constructor
    m5stackScannableContext() = default;

    // Destructor
    virtual ~m5stackScannableContext() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackScannableContext(const m5stackScannableContext&) = delete;
    m5stackScannableContext& operator=(const m5stackScannableContext&) = delete;

    // Delete move constructor and assignment operator
    m5stackScannableContext(m5stackScannableContext&&) = delete;
    m5stackScannableContext& operator=(m5stackScannableContext&&) = delete;

    // Override pure virtual methods from base class

    BluetoothContext get_bluetooth_context() const override;

    WiFiContext get_wifi_context() const override;

    BLEContext get_ble_context() const override;

};


} // namespace omusubi

