// Header file for m5stackPowerContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "power_context.h"


namespace omusubi {


/**
 * @brief m5stackPowerContext - Implementation of PowerContext
 *
 * This class implements the pure virtual functions from PowerContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackPowerContext : public PowerContext {
public:
    // Constructor
    m5stackPowerContext() = default;

    // Destructor
    virtual ~m5stackPowerContext() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackPowerContext(const m5stackPowerContext&) = delete;
    m5stackPowerContext& operator=(const m5stackPowerContext&) = delete;

    // Delete move constructor and assignment operator
    m5stackPowerContext(m5stackPowerContext&&) = delete;
    m5stackPowerContext& operator=(m5stackPowerContext&&) = delete;

    // Override pure virtual methods from base class

    PowerState get_power_state() const override;

    uint8_t get_battery_level() const override;

    bool is_charging() const override;

};


} // namespace omusubi

