// Header file for M5StackByteReadable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "byte_readable.h"


namespace omusubi {


/**
 * @brief M5StackByteReadable - Implementation of ByteReadable
 *
 * This class implements the pure virtual functions from ByteReadable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackByteReadable : public ByteReadable {
public:
    // Constructor
    M5StackByteReadable() = default;

    // Destructor
    virtual ~M5StackByteReadable() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackByteReadable(const M5StackByteReadable&) = delete;
    M5StackByteReadable& operator=(const M5StackByteReadable&) = delete;

    // Delete move constructor and assignment operator
    M5StackByteReadable(M5StackByteReadable&&) = delete;
    M5StackByteReadable& operator=(M5StackByteReadable&&) = delete;

    // Override pure virtual methods from base class

    size_t read(span<uint8_t> buffer) override;

    size_t available() const override;

};


} // namespace omusubi

