// Header file for m5stackTextWritable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "text_writable.h"


namespace omusubi {


/**
 * @brief m5stackTextWritable - Implementation of TextWritable
 *
 * This class implements the pure virtual functions from TextWritable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackTextWritable : public TextWritable {
public:
    // Constructor
    m5stackTextWritable() = default;

    // Destructor
    virtual ~m5stackTextWritable() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackTextWritable(const m5stackTextWritable&) = delete;
    m5stackTextWritable& operator=(const m5stackTextWritable&) = delete;

    // Delete move constructor and assignment operator
    m5stackTextWritable(m5stackTextWritable&&) = delete;
    m5stackTextWritable& operator=(m5stackTextWritable&&) = delete;

    // Override pure virtual methods from base class

    size_t write_text(span<const char> text) const override;

};


} // namespace omusubi

