// Header file for m5stackMeasurable3D
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "measurable3d.h"


namespace omusubi {


/**
 * @brief m5stackMeasurable3D - Implementation of Measurable3D
 *
 * This class implements the pure virtual functions from Measurable3D.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackMeasurable3D : public Measurable3D {
public:
    // Constructor
    m5stackMeasurable3D() = default;

    // Destructor
    virtual ~m5stackMeasurable3D() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackMeasurable3D(const m5stackMeasurable3D&) = delete;
    m5stackMeasurable3D& operator=(const m5stackMeasurable3D&) = delete;

    // Delete move constructor and assignment operator
    m5stackMeasurable3D(m5stackMeasurable3D&&) = delete;
    m5stackMeasurable3D& operator=(m5stackMeasurable3D&&) = delete;

    // Override pure virtual methods from base class

    Vector3 get_values() const override;

};


} // namespace omusubi

