// Header file for m5stackConnectable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "connectable.h"


namespace omusubi {


/**
 * @brief m5stackConnectable - Implementation of Connectable
 *
 * This class implements the pure virtual functions from Connectable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackConnectable : public Connectable {
public:
    // Constructor
    m5stackConnectable() = default;

    // Destructor
    virtual ~m5stackConnectable() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackConnectable(const m5stackConnectable&) = delete;
    m5stackConnectable& operator=(const m5stackConnectable&) = delete;

    // Delete move constructor and assignment operator
    m5stackConnectable(m5stackConnectable&&) = delete;
    m5stackConnectable& operator=(m5stackConnectable&&) = delete;

    // Override pure virtual methods from base class

    bool connect() override;

    bool disconnect() override;

    bool is_connected() const override;

};


} // namespace omusubi

