// Header file for m5stackDisplayable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "displayable.h"


namespace omusubi {


/**
 * @brief m5stackDisplayable - Implementation of Displayable
 *
 * This class implements the pure virtual functions from Displayable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackDisplayable : public Displayable {
public:
    // Constructor
    m5stackDisplayable() = default;

    // Destructor
    virtual ~m5stackDisplayable() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackDisplayable(const m5stackDisplayable&) = delete;
    m5stackDisplayable& operator=(const m5stackDisplayable&) = delete;

    // Delete move constructor and assignment operator
    m5stackDisplayable(m5stackDisplayable&&) = delete;
    m5stackDisplayable& operator=(m5stackDisplayable&&) = delete;

    // Override pure virtual methods from base class

    void display(std::string_view text) override;

};


} // namespace omusubi

