// Header file for m5stackByteWritable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "byte_writable.h"


namespace omusubi {


/**
 * @brief m5stackByteWritable - Implementation of ByteWritable
 *
 * This class implements the pure virtual functions from ByteWritable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackByteWritable : public ByteWritable {
public:
    // Constructor
    m5stackByteWritable() = default;

    // Destructor
    virtual ~m5stackByteWritable() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackByteWritable(const m5stackByteWritable&) = delete;
    m5stackByteWritable& operator=(const m5stackByteWritable&) = delete;

    // Delete move constructor and assignment operator
    m5stackByteWritable(m5stackByteWritable&&) = delete;
    m5stackByteWritable& operator=(m5stackByteWritable&&) = delete;

    // Override pure virtual methods from base class

    size_t write(span<const uint8_t> data) const override;

};


} // namespace omusubi

