// Header file for m5stackConnectableContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "connectable_context.h"


namespace omusubi {


/**
 * @brief m5stackConnectableContext - Implementation of ConnectableContext
 *
 * This class implements the pure virtual functions from ConnectableContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackConnectableContext : public ConnectableContext {
public:
    // Constructor
    m5stackConnectableContext() = default;

    // Destructor
    virtual ~m5stackConnectableContext() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackConnectableContext(const m5stackConnectableContext&) = delete;
    m5stackConnectableContext& operator=(const m5stackConnectableContext&) = delete;

    // Delete move constructor and assignment operator
    m5stackConnectableContext(m5stackConnectableContext&&) = delete;
    m5stackConnectableContext& operator=(m5stackConnectableContext&&) = delete;

    // Override pure virtual methods from base class

    SerialContext get_serial_context(uint8_t port) const override;

    uint8_t get_serial_count() const override;

    BluetoothContext get_bluetooth_context() const override;

    WiFiContext get_wifi_context() const override;

    BLEContext get_ble_context() const override;

};


} // namespace omusubi

