// Header file for m5stackTextReadable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "text_readable.h"


namespace omusubi {


/**
 * @brief m5stackTextReadable - Implementation of TextReadable
 *
 * This class implements the pure virtual functions from TextReadable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackTextReadable : public TextReadable {
public:
    // Constructor
    m5stackTextReadable() = default;

    // Destructor
    virtual ~m5stackTextReadable() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackTextReadable(const m5stackTextReadable&) = delete;
    m5stackTextReadable& operator=(const m5stackTextReadable&) = delete;

    // Delete move constructor and assignment operator
    m5stackTextReadable(m5stackTextReadable&&) = delete;
    m5stackTextReadable& operator=(m5stackTextReadable&&) = delete;

    // Override pure virtual methods from base class

    size_t read_line(span<char> buffer) override;

};


} // namespace omusubi

