// Header file for m5stackByteReadable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "byte_readable.h"


namespace omusubi {


/**
 * @brief m5stackByteReadable - Implementation of ByteReadable
 *
 * This class implements the pure virtual functions from ByteReadable.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class m5stackByteReadable : public ByteReadable {
public:
    // Constructor
    m5stackByteReadable() = default;

    // Destructor
    virtual ~m5stackByteReadable() noexcept = default;

    // Delete copy constructor and assignment operator
    m5stackByteReadable(const m5stackByteReadable&) = delete;
    m5stackByteReadable& operator=(const m5stackByteReadable&) = delete;

    // Delete move constructor and assignment operator
    m5stackByteReadable(m5stackByteReadable&&) = delete;
    m5stackByteReadable& operator=(m5stackByteReadable&&) = delete;

    // Override pure virtual methods from base class

    size_t read(span<uint8_t> buffer) override;

    size_t available() const override;

};


} // namespace omusubi

