// Header file for M5StackWiFiContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

#include "wi_fi_context.h"


namespace omusubi {


/**
 * @brief M5StackWiFiContext - Implementation of WiFiContext
 *
 * This class implements the pure virtual functions from WiFiContext.
 * All method bodies are left empty for manual implementation.
 *
 * @note C++17 compliant implementation
 */
class M5StackWiFiContext : public WiFiContext {
public:
    // Constructor
    M5StackWiFiContext() = default;

    // Destructor
    virtual ~M5StackWiFiContext() noexcept = default;

    // Delete copy constructor and assignment operator
    M5StackWiFiContext(const M5StackWiFiContext&) = delete;
    M5StackWiFiContext& operator=(const M5StackWiFiContext&) = delete;

    // Delete move constructor and assignment operator
    M5StackWiFiContext(M5StackWiFiContext&&) = delete;
    M5StackWiFiContext& operator=(M5StackWiFiContext&&) = delete;

    // Override pure virtual methods from base class

    bool connect() override;

    bool disconnect() override;

    bool is_connected() const override;

    bool start_scan() override;

    bool stop_scan() override;

    uint8_t get_found_count() const override;

    std::string_view get_found_name(uint8_t index) const override;

    int32_t get_found_signal_strength(uint8_t index) const override;

};


} // namespace omusubi

