// Implementation file for m5stackByteReadable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_byte_readable.h"


namespace omusubi {



size_t m5stackByteReadable::read(span<uint8_t> buffer) {
    // TODO: Implement read
}


size_t m5stackByteReadable::available() const {
    // TODO: Implement available
}



} // namespace omusubi

