// Implementation file for m5stackBluetoothContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_bluetooth_context.h"


namespace omusubi {



size_t m5stackBluetoothContext::read(span<uint8_t> buffer) {
    // TODO: Implement read
}


size_t m5stackBluetoothContext::available() const {
    // TODO: Implement available
}


size_t m5stackBluetoothContext::read_line(span<char> buffer) {
    // TODO: Implement read_line
}


size_t m5stackBluetoothContext::write(span<const uint8_t> data) const {
    // TODO: Implement write
}


size_t m5stackBluetoothContext::write_text(span<const char> text) const {
    // TODO: Implement write_text
}


bool m5stackBluetoothContext::connect() {
    // TODO: Implement connect
}


bool m5stackBluetoothContext::disconnect() {
    // TODO: Implement disconnect
}


bool m5stackBluetoothContext::is_connected() const {
    // TODO: Implement is_connected
}


bool m5stackBluetoothContext::start_scan() {
    // TODO: Implement start_scan
}


bool m5stackBluetoothContext::stop_scan() {
    // TODO: Implement stop_scan
}


uint8_t m5stackBluetoothContext::get_found_count() const {
    // TODO: Implement get_found_count
}


std::string_view m5stackBluetoothContext::get_found_name(uint8_t index) const {
    // TODO: Implement get_found_name
}


int32_t m5stackBluetoothContext::get_found_signal_strength(uint8_t index) const {
    // TODO: Implement get_found_signal_strength
}



} // namespace omusubi

