// Implementation file for M5StackByteReadable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_byte_readable.h"


namespace omusubi {



size_t M5StackByteReadable::read(span<uint8_t> buffer) {
    // TODO: Implement read
}


size_t M5StackByteReadable::available() const {
    // TODO: Implement available
}



} // namespace omusubi

