// Implementation file for M5StackBLECharacteristic
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_blecharacteristic.h"


namespace omusubi {



size_t M5StackBLECharacteristic::read(span<uint8_t> buffer) {
    // TODO: Implement read
}


size_t M5StackBLECharacteristic::available() const {
    // TODO: Implement available
}


size_t M5StackBLECharacteristic::write(span<const uint8_t> data) const {
    // TODO: Implement write
}



} // namespace omusubi

