// Implementation file for m5stackConnectableContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_connectable_context.h"


namespace omusubi {



SerialContext m5stackConnectableContext::get_serial_context(uint8_t port) const {
    // TODO: Implement get_serial_context
}


uint8_t m5stackConnectableContext::get_serial_count() const {
    // TODO: Implement get_serial_count
}


BluetoothContext m5stackConnectableContext::get_bluetooth_context() const {
    // TODO: Implement get_bluetooth_context
}


WiFiContext m5stackConnectableContext::get_wifi_context() const {
    // TODO: Implement get_wifi_context
}


BLEContext m5stackConnectableContext::get_ble_context() const {
    // TODO: Implement get_ble_context
}



} // namespace omusubi

