// Implementation file for m5stackMeasurable1D
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_measurable1d.h"


namespace omusubi {



float m5stackMeasurable1D::get_value() const {
    // TODO: Implement get_value
}



} // namespace omusubi

