// Implementation file for M5StackTextWritable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_text_writable.h"


namespace omusubi {



size_t M5StackTextWritable::write_text(span<const char> text) const {
    // TODO: Implement write_text
}



} // namespace omusubi

