// Implementation file for M5StackScannable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_scannable.h"


namespace omusubi {



bool M5StackScannable::start_scan() {
    // TODO: Implement start_scan
}


bool M5StackScannable::stop_scan() {
    // TODO: Implement stop_scan
}


uint8_t M5StackScannable::get_found_count() const {
    // TODO: Implement get_found_count
}


std::string_view M5StackScannable::get_found_name(uint8_t index) const {
    // TODO: Implement get_found_name
}


int32_t M5StackScannable::get_found_signal_strength(uint8_t index) const {
    // TODO: Implement get_found_signal_strength
}



} // namespace omusubi

