// Implementation file for M5StackByteWritable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_byte_writable.h"


namespace omusubi {



size_t M5StackByteWritable::write(span<const uint8_t> data) const {
    // TODO: Implement write
}



} // namespace omusubi

