// Implementation file for m5stackPressable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_pressable.h"


namespace omusubi {



ButtonState m5stackPressable::get_state() const {
    // TODO: Implement get_state
}



} // namespace omusubi

