// Implementation file for m5stackLogOutput
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_log_output.h"


namespace omusubi {



void m5stackLogOutput::write(LogLevel level, std::string_view message) {
    // TODO: Implement write
}



} // namespace omusubi

