// Implementation file for m5stackTextReadable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_text_readable.h"


namespace omusubi {



size_t m5stackTextReadable::read_line(span<char> buffer) {
    // TODO: Implement read_line
}



} // namespace omusubi

