// Implementation file for M5StackSerialContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_serial_context.h"


namespace omusubi {



size_t M5StackSerialContext::read(span<uint8_t> buffer) {
    // TODO: Implement read
}


size_t M5StackSerialContext::available() const {
    // TODO: Implement available
}


size_t M5StackSerialContext::read_line(span<char> buffer) {
    // TODO: Implement read_line
}


size_t M5StackSerialContext::write(span<const uint8_t> data) const {
    // TODO: Implement write
}


size_t M5StackSerialContext::write_text(span<const char> text) const {
    // TODO: Implement write_text
}


bool M5StackSerialContext::connect() {
    // TODO: Implement connect
}


bool M5StackSerialContext::disconnect() {
    // TODO: Implement disconnect
}


bool M5StackSerialContext::is_connected() const {
    // TODO: Implement is_connected
}



} // namespace omusubi

