// Implementation file for m5stackTextWritable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_text_writable.h"


namespace omusubi {



size_t m5stackTextWritable::write_text(span<const char> text) const {
    // TODO: Implement write_text
}



} // namespace omusubi

