// Implementation file for m5stackSerialContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_serial_context.h"


namespace omusubi {



size_t m5stackSerialContext::read(span<uint8_t> buffer) {
    // TODO: Implement read
}


size_t m5stackSerialContext::available() const {
    // TODO: Implement available
}


size_t m5stackSerialContext::read_line(span<char> buffer) {
    // TODO: Implement read_line
}


size_t m5stackSerialContext::write(span<const uint8_t> data) const {
    // TODO: Implement write
}


size_t m5stackSerialContext::write_text(span<const char> text) const {
    // TODO: Implement write_text
}


bool m5stackSerialContext::connect() {
    // TODO: Implement connect
}


bool m5stackSerialContext::disconnect() {
    // TODO: Implement disconnect
}


bool m5stackSerialContext::is_connected() const {
    // TODO: Implement is_connected
}



} // namespace omusubi

