// Implementation file for m5stackByteWritable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_byte_writable.h"


namespace omusubi {



size_t m5stackByteWritable::write(span<const uint8_t> data) const {
    // TODO: Implement write
}



} // namespace omusubi

