// Implementation file for M5StackConnectableContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_connectable_context.h"


namespace omusubi {



SerialContext M5StackConnectableContext::get_serial_context(uint8_t port) const {
    // TODO: Implement get_serial_context
}


uint8_t M5StackConnectableContext::get_serial_count() const {
    // TODO: Implement get_serial_count
}


BluetoothContext M5StackConnectableContext::get_bluetooth_context() const {
    // TODO: Implement get_bluetooth_context
}


WiFiContext M5StackConnectableContext::get_wifi_context() const {
    // TODO: Implement get_wifi_context
}


BLEContext M5StackConnectableContext::get_ble_context() const {
    // TODO: Implement get_ble_context
}



} // namespace omusubi

