// Implementation file for m5stackMeasurable3D
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_measurable3d.h"


namespace omusubi {



Vector3 m5stackMeasurable3D::get_values() const {
    // TODO: Implement get_values
}



} // namespace omusubi

