// Implementation file for M5StackLogOutput
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_log_output.h"


namespace omusubi {



void M5StackLogOutput::write(LogLevel level, std::string_view message) {
    // TODO: Implement write
}



} // namespace omusubi

