// Implementation file for m5stackScannableContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_scannable_context.h"


namespace omusubi {



BluetoothContext m5stackScannableContext::get_bluetooth_context() const {
    // TODO: Implement get_bluetooth_context
}


WiFiContext m5stackScannableContext::get_wifi_context() const {
    // TODO: Implement get_wifi_context
}


BLEContext m5stackScannableContext::get_ble_context() const {
    // TODO: Implement get_ble_context
}



} // namespace omusubi

