// Implementation file for M5StackDisplayable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_displayable.h"


namespace omusubi {



void M5StackDisplayable::display(std::string_view text) {
    // TODO: Implement display
}



} // namespace omusubi

