// Implementation file for m5stackScannable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_scannable.h"


namespace omusubi {



bool m5stackScannable::start_scan() {
    // TODO: Implement start_scan
}


bool m5stackScannable::stop_scan() {
    // TODO: Implement stop_scan
}


uint8_t m5stackScannable::get_found_count() const {
    // TODO: Implement get_found_count
}


std::string_view m5stackScannable::get_found_name(uint8_t index) const {
    // TODO: Implement get_found_name
}


int32_t m5stackScannable::get_found_signal_strength(uint8_t index) const {
    // TODO: Implement get_found_signal_strength
}



} // namespace omusubi

