// Implementation file for M5StackMeasurable3D
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_measurable3d.h"


namespace omusubi {



Vector3 M5StackMeasurable3D::get_values() const {
    // TODO: Implement get_values
}



} // namespace omusubi

