// Implementation file for M5StackScannableContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_scannable_context.h"


namespace omusubi {



BluetoothContext M5StackScannableContext::get_bluetooth_context() const {
    // TODO: Implement get_bluetooth_context
}


WiFiContext M5StackScannableContext::get_wifi_context() const {
    // TODO: Implement get_wifi_context
}


BLEContext M5StackScannableContext::get_ble_context() const {
    // TODO: Implement get_ble_context
}



} // namespace omusubi

