// Implementation file for M5StackTextReadable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_text_readable.h"


namespace omusubi {



size_t M5StackTextReadable::read_line(span<char> buffer) {
    // TODO: Implement read_line
}



} // namespace omusubi

