// Implementation file for m5stackBLECharacteristic
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_blecharacteristic.h"


namespace omusubi {



size_t m5stackBLECharacteristic::read(span<uint8_t> buffer) {
    // TODO: Implement read
}


size_t m5stackBLECharacteristic::available() const {
    // TODO: Implement available
}


size_t m5stackBLECharacteristic::write(span<const uint8_t> data) const {
    // TODO: Implement write
}



} // namespace omusubi

