// Implementation file for M5StackPressable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_pressable.h"


namespace omusubi {



ButtonState M5StackPressable::get_state() const {
    // TODO: Implement get_state
}



} // namespace omusubi

