// Implementation file for M5StackBluetoothContext
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "M5Stack_bluetooth_context.h"


namespace omusubi {



size_t M5StackBluetoothContext::read(span<uint8_t> buffer) {
    // TODO: Implement read
}


size_t M5StackBluetoothContext::available() const {
    // TODO: Implement available
}


size_t M5StackBluetoothContext::read_line(span<char> buffer) {
    // TODO: Implement read_line
}


size_t M5StackBluetoothContext::write(span<const uint8_t> data) const {
    // TODO: Implement write
}


size_t M5StackBluetoothContext::write_text(span<const char> text) const {
    // TODO: Implement write_text
}


bool M5StackBluetoothContext::connect() {
    // TODO: Implement connect
}


bool M5StackBluetoothContext::disconnect() {
    // TODO: Implement disconnect
}


bool M5StackBluetoothContext::is_connected() const {
    // TODO: Implement is_connected
}


bool M5StackBluetoothContext::start_scan() {
    // TODO: Implement start_scan
}


bool M5StackBluetoothContext::stop_scan() {
    // TODO: Implement stop_scan
}


uint8_t M5StackBluetoothContext::get_found_count() const {
    // TODO: Implement get_found_count
}


std::string_view M5StackBluetoothContext::get_found_name(uint8_t index) const {
    // TODO: Implement get_found_name
}


int32_t M5StackBluetoothContext::get_found_signal_strength(uint8_t index) const {
    // TODO: Implement get_found_signal_strength
}



} // namespace omusubi

