// Implementation file for m5stackDisplayable
// Auto-generated by omusubi-codegen
// DO NOT EDIT THIS FILE MANUALLY

#include "m5stack_displayable.h"


namespace omusubi {



void m5stackDisplayable::display(std::string_view text) {
    // TODO: Implement display
}



} // namespace omusubi

